from __future__ import annotations

import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from slipform.cloud_init import initialize_database
from slipform.http.legacy_server import resolve_runtime_config
from slipform.repositories import schema
from slipform.repositories.connection import connect, database_engine
from slipform.services.backups import create_sqlite_backup

ROOT = Path(__file__).resolve().parents[1]


class CloudDeployTests(unittest.TestCase):
    def setUp(self) -> None:
        self.old_database_url = os.environ.pop("DATABASE_URL", None)

    def tearDown(self) -> None:
        if self.old_database_url is not None:
            os.environ["DATABASE_URL"] = self.old_database_url
        else:
            os.environ.pop("DATABASE_URL", None)

    def test_connect_uses_sqlite_without_database_url(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            with connect(Path(tmp) / "slipform.sqlite") as conn:
                self.assertEqual(database_engine(conn), "sqlite")

    def test_connect_uses_postgres_with_database_url(self) -> None:
        fake_psycopg = _FakePsycopg()
        with patch.dict(sys.modules, {"psycopg": fake_psycopg}):
            os.environ["DATABASE_URL"] = "postgresql://user:pass@localhost/db"

            conn = connect(Path("ignored.sqlite"))
            cursor = conn.execute("SELECT * FROM colados WHERE id = ?", (7,))

            self.assertEqual(database_engine(conn), "postgres")
            self.assertEqual(fake_psycopg.raw.last_cursor.sql, "SELECT * FROM colados WHERE id = %s")
            self.assertEqual(fake_psycopg.raw.last_cursor.params, (7,))
            self.assertEqual(cursor.fetchall(), [])

    def test_cloud_init_creates_clean_sqlite_without_curves_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            db_path = Path(tmp) / "slipform.sqlite"
            missing_curves = Path(tmp) / "Curvas HRP.xlsx"

            result = initialize_database(db_path, missing_curves)

            self.assertEqual(result["imported_curves"], 0)
            self.assertEqual(result["curve_count"], 0)
            self.assertGreaterEqual(result["project_count"], 1)
            with connect(db_path) as conn:
                tables = {
                    row["name"]
                    for row in conn.execute("SELECT name FROM sqlite_master WHERE type = 'table'").fetchall()
                }
                self.assertIn("colados", tables)
                self.assertIn("proyectos", tables)

    def test_cloud_init_imports_curves_once(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            db_path = Path(tmp) / "slipform.sqlite"
            curves_path = ROOT / "Curvas HRP.xlsx"

            first = initialize_database(db_path, curves_path)
            second = initialize_database(db_path, curves_path)

            self.assertEqual(first["engine"], "sqlite")
            self.assertGreater(first["imported_curves"], 0)
            self.assertEqual(second["imported_curves"], 0)
            self.assertEqual(second["curve_count"], first["curve_count"])

    def test_init_db_uses_postgres_schema_for_postgres_connection(self) -> None:
        conn = _FakePostgresConnection()

        schema.init_db(conn)

        ddl = "\n".join(conn.statements)
        self.assertIn("CREATE TABLE IF NOT EXISTS colados", ddl)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", ddl)
        self.assertNotIn("AUTOINCREMENT", ddl)
        self.assertNotIn("PRAGMA", ddl)

    def test_postgres_backup_endpoint_returns_managed_notice(self) -> None:
        os.environ["DATABASE_URL"] = "postgresql://user:pass@localhost/db"

        backup = create_sqlite_backup(Path("ignored.sqlite"), "unit_test")

        self.assertEqual(backup["tipo"], "postgres_render")
        self.assertFalse(backup["disponible"])

    def test_runtime_config_uses_render_port_and_host_env(self) -> None:
        old_host = os.environ.get("SLIPFORM_HOST")
        old_port = os.environ.get("PORT")
        try:
            os.environ["SLIPFORM_HOST"] = "0.0.0.0"
            os.environ["PORT"] = "10000"

            host, port = resolve_runtime_config()

            self.assertEqual(host, "0.0.0.0")
            self.assertEqual(port, 10000)
        finally:
            if old_host is None:
                os.environ.pop("SLIPFORM_HOST", None)
            else:
                os.environ["SLIPFORM_HOST"] = old_host
            if old_port is None:
                os.environ.pop("PORT", None)
            else:
                os.environ["PORT"] = old_port

    def test_render_blueprint_contract(self) -> None:
        text = (ROOT / "render.yaml").read_text(encoding="utf-8")

        self.assertIn("runtime: python", text)
        self.assertNotIn("preDeployCommand", text)
        self.assertIn("startCommand: python -m slipform.server", text)
        self.assertIn("healthCheckPath: /api/health", text)
        self.assertIn("DATABASE_URL", text)
        self.assertIn("fromDatabase:", text)
        self.assertIn("name: deslizados-labsico-db", text)
        self.assertIn("plan: basic-256mb", text)
        self.assertNotIn("SLIPFORM_DB_PATH", text)
        self.assertNotIn("mountPath: /var/data", text)


class _FakeColumn:
    def __init__(self, name: str) -> None:
        self.name = name


class _FakeCursor:
    description: list[_FakeColumn] = []

    def __init__(self) -> None:
        self.sql = ""
        self.params = ()
        self.rowcount = 0

    def execute(self, sql: str, params=()) -> None:
        self.sql = sql
        self.params = tuple(params)

    def executemany(self, sql: str, params_seq) -> None:
        self.sql = sql
        self.params = tuple(params_seq)

    def fetchone(self):
        return None

    def fetchall(self):
        return []


class _FakeRawPostgres:
    def __init__(self) -> None:
        self.last_cursor = _FakeCursor()

    def cursor(self) -> _FakeCursor:
        self.last_cursor = _FakeCursor()
        return self.last_cursor

    def commit(self) -> None:
        pass

    def rollback(self) -> None:
        pass

    def close(self) -> None:
        pass


class _FakePsycopg:
    def __init__(self) -> None:
        self.raw = _FakeRawPostgres()

    def connect(self, dsn: str) -> _FakeRawPostgres:
        return self.raw


class _FakePostgresConnection:
    engine = "postgres"

    def __init__(self) -> None:
        self.statements: list[str] = []
        self.committed = False

    def execute(self, sql: str, params=()):
        self.statements.append(sql)
        return _FakeCursor()

    def commit(self) -> None:
        self.committed = True


if __name__ == "__main__":
    unittest.main()
