"""PostgreSQL schema creation for Render deployments."""

from __future__ import annotations

from datetime import datetime

from slipform.config import DEFAULT_ADVANCE_CM, DEFAULT_ADVANCE_SPEED_CM_H

SCHEMA_VERSION = 9
SCHEMA_DESCRIPTION = "postgres_render_initial"


POSTGRES_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS schema_migrations (
        version INTEGER PRIMARY KEY,
        applied_at TEXT NOT NULL,
        description TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS auditoria_operativa (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha_hora TEXT NOT NULL,
        accion TEXT NOT NULL,
        entidad TEXT NOT NULL,
        entidad_id INTEGER,
        colado_id INTEGER,
        operador TEXT,
        motivo TEXT,
        detalle_json TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS mezclas (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL,
        cemento TEXT,
        aditivo TEXT,
        dosificacion_hrp_cc DOUBLE PRECISION,
        relacion_agua_cemento DOUBLE PRECISION,
        observaciones TEXT,
        UNIQUE(nombre, dosificacion_hrp_cc)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS proyectos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL UNIQUE,
        cliente TEXT,
        obra TEXT,
        ubicacion TEXT,
        elemento TEXT,
        contratista TEXT,
        supervisor TEXT,
        logo_izquierdo TEXT,
        logo_derecho TEXT,
        altura_objetivo_m DOUBLE PRECISION,
        nivel_inicial_m DOUBLE PRECISION,
        nivel_final_m DOUBLE PRECISION,
        volumen_estimado_m3 DOUBLE PRECISION,
        area_cimbra_m2 DOUBLE PRECISION,
        fecha_inicio_programada TEXT,
        fecha_fin_programada TEXT,
        activo INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS curvas_laboratorio (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        mezcla_id INTEGER NOT NULL REFERENCES mezclas(id),
        origen_archivo TEXT NOT NULL,
        nombre_curva TEXT NOT NULL,
        fecha_ensayo TEXT,
        madurez_objetivo_h_eq DOUBLE PRECISION NOT NULL,
        parametros_json TEXT NOT NULL,
        UNIQUE(origen_archivo, nombre_curva)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS curvas_laboratorio_puntos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        curva_id INTEGER NOT NULL REFERENCES curvas_laboratorio(id) ON DELETE CASCADE,
        minuto DOUBLE PRECISION NOT NULL,
        temperatura_concreto_c DOUBLE PRECISION NOT NULL,
        madurez_arrhenius_h_eq DOUBLE PRECISION NOT NULL,
        UNIQUE(curva_id, minuto)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS colados (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        proyecto_id INTEGER REFERENCES proyectos(id) ON DELETE SET NULL,
        silo_id TEXT NOT NULL,
        mezcla_id INTEGER NOT NULL REFERENCES mezclas(id),
        curva_id INTEGER REFERENCES curvas_laboratorio(id),
        fecha_hora_inicio TEXT NOT NULL,
        hora_salida_planta TEXT,
        hora_llegada_obra TEXT,
        hora_inicio_descarga TEXT,
        hora_colocacion_en_molde TEXT,
        hora_fin_descarga TEXT,
        fecha_cierre TEXT,
        operador TEXT,
        estado TEXT NOT NULL DEFAULT 'ACTIVO',
        es_demo INTEGER NOT NULL DEFAULT 0,
        observaciones TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sensores (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tipo TEXT NOT NULL,
        variable TEXT NOT NULL,
        ubicacion TEXT,
        silo_id TEXT,
        activo INTEGER NOT NULL DEFAULT 1,
        fecha_calibracion TEXT,
        observaciones TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS descargas_olla (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        numero_olla TEXT NOT NULL,
        volumen_m3 DOUBLE PRECISION NOT NULL DEFAULT 5.0,
        hora_salida_planta TEXT,
        hora_llegada_obra TEXT,
        hora_inicio_descarga TEXT,
        hora_fin_descarga TEXT,
        temperatura_salida_c DOUBLE PRECISION,
        temperatura_llegada_c DOUBLE PRECISION,
        revenimiento_cm DOUBLE PRECISION,
        origen_generacion TEXT NOT NULL DEFAULT 'manual',
        estado_operativo TEXT NOT NULL DEFAULT 'CONFIRMADA_EN_MOLDE',
        observaciones TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS avances_molde (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        receta_avance_id INTEGER,
        fecha_hora TEXT NOT NULL,
        minuto_transcurrido DOUBLE PRECISION NOT NULL,
        avance_cm DOUBLE PRECISION NOT NULL,
        avance_acumulado_cm DOUBLE PRECISION NOT NULL,
        velocidad_real_cm_h DOUBLE PRECISION,
        intervalo_minutos DOUBLE PRECISION,
        origen TEXT NOT NULL DEFAULT 'manual',
        observacion TEXT,
        operador TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS zonas_colado (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        descarga_olla_id INTEGER REFERENCES descargas_olla(id) ON DELETE SET NULL,
        zona_numero INTEGER NOT NULL,
        elevacion_inferior_cm DOUBLE PRECISION NOT NULL,
        elevacion_superior_cm DOUBLE PRECISION NOT NULL,
        volumen_m3 DOUBLE PRECISION NOT NULL DEFAULT 5.0,
        hora_salida_planta TEXT,
        hora_inicio_llenado TEXT NOT NULL,
        hora_fin_llenado TEXT,
        hora_referencia_madurez TEXT NOT NULL,
        mezcla_id INTEGER REFERENCES mezclas(id),
        curva_id INTEGER REFERENCES curvas_laboratorio(id),
        temperatura_inicial_c DOUBLE PRECISION,
        origen_generacion TEXT NOT NULL DEFAULT 'manual',
        avance_generador_id INTEGER REFERENCES avances_molde(id) ON DELETE SET NULL,
        estado TEXT NOT NULL DEFAULT 'ZONA_EN_LLENADO'
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS lecturas (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        sensor_id INTEGER REFERENCES sensores(id),
        fecha_hora TEXT NOT NULL,
        minuto_transcurrido DOUBLE PRECISION NOT NULL,
        temperatura_concreto_c DOUBLE PRECISION,
        temperatura_ambiente_c DOUBLE PRECISION,
        humedad_relativa_pct DOUBLE PRECISION,
        origen TEXT NOT NULL CHECK(origen IN ('manual', 'sensor', 'importacion', 'estimado')),
        valido INTEGER NOT NULL DEFAULT 1,
        motivo_invalidez TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS predicciones (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        fecha_hora TEXT NOT NULL,
        madurez_acumulada_h_eq DOUBLE PRECISION NOT NULL,
        avance DOUBLE PRECISION NOT NULL,
        estado TEXT NOT NULL,
        minutos_restantes DOUBLE PRECISION,
        desviacion_vs_laboratorio DOUBLE PRECISION,
        alertas_json TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS eventos_deslizamiento (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        fecha_hora TEXT NOT NULL,
        minuto_transcurrido DOUBLE PRECISION NOT NULL,
        velocidad_deslizamiento_cm_h DOUBLE PRECISION,
        decision_tomada TEXT NOT NULL,
        resultado_fisico TEXT NOT NULL,
        checklist_no_desmorona INTEGER NOT NULL DEFAULT 0,
        checklist_no_se_pega INTEGER NOT NULL DEFAULT 0,
        checklist_acabado_aceptable INTEGER NOT NULL DEFAULT 0,
        checklist_sin_arrastre INTEGER NOT NULL DEFAULT 0,
        observacion TEXT,
        supervisor TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS configuracion_molde (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL UNIQUE,
        altura_molde_m DOUBLE PRECISION NOT NULL,
        altura_zona_m DOUBLE PRECISION NOT NULL,
        zonas_por_molde INTEGER NOT NULL,
        velocidad_objetivo_cm_h DOUBLE PRECISION NOT NULL,
        avance_objetivo_cm_5min DOUBLE PRECISION NOT NULL,
        residencia_minima_h DOUBLE PRECISION NOT NULL,
        residencia_preferente_h DOUBLE PRECISION NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS recetas_avance_colado (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        fecha_hora TEXT NOT NULL,
        avance_objetivo_cm DOUBLE PRECISION NOT NULL,
        intervalo_objetivo_min DOUBLE PRECISION NOT NULL,
        velocidad_objetivo_cm_h DOUBLE PRECISION NOT NULL,
        tolerancia_velocidad_min_cm_h DOUBLE PRECISION NOT NULL,
        tolerancia_velocidad_max_cm_h DOUBLE PRECISION NOT NULL,
        activo INTEGER NOT NULL DEFAULT 1,
        motivo TEXT,
        operador TEXT,
        supervisor TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS lecturas_zona (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        zona_colado_id INTEGER NOT NULL REFERENCES zonas_colado(id) ON DELETE CASCADE,
        sensor_id INTEGER REFERENCES sensores(id),
        fecha_hora TEXT NOT NULL,
        minuto_desde_zona DOUBLE PRECISION NOT NULL,
        temperatura_concreto_c DOUBLE PRECISION,
        temperatura_ambiente_c DOUBLE PRECISION,
        humedad_relativa_pct DOUBLE PRECISION,
        origen TEXT NOT NULL CHECK(origen IN ('manual', 'sensor', 'importacion', 'estimado')),
        valido INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS alarmas_operativas (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        zona_colado_id INTEGER REFERENCES zonas_colado(id) ON DELETE SET NULL,
        tipo TEXT NOT NULL,
        severidad TEXT NOT NULL,
        estado TEXT NOT NULL DEFAULT 'ACTIVA',
        fecha_hora_inicio TEXT NOT NULL,
        fecha_hora_reconocimiento TEXT,
        fecha_hora_cierre TEXT,
        operador_reconoce TEXT,
        mensaje TEXT NOT NULL,
        UNIQUE(colado_id, zona_colado_id, tipo, fecha_hora_inicio)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS decisiones_operador (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        zona_colado_id INTEGER REFERENCES zonas_colado(id) ON DELETE SET NULL,
        avance_molde_id INTEGER REFERENCES avances_molde(id) ON DELETE SET NULL,
        fecha_hora TEXT NOT NULL,
        recomendacion_sistema TEXT NOT NULL,
        decision_operador TEXT NOT NULL,
        conforme_recomendacion INTEGER NOT NULL DEFAULT 1,
        requiere_supervisor INTEGER NOT NULL DEFAULT 0,
        operador TEXT,
        supervisor TEXT,
        checklist_json TEXT NOT NULL,
        observacion TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS liberaciones_campo (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        zona_colado_id INTEGER NOT NULL REFERENCES zonas_colado(id) ON DELETE CASCADE,
        fecha_hora TEXT NOT NULL,
        madurez_calculada_pct DOUBLE PRECISION NOT NULL,
        madurez_operativa_pct DOUBLE PRECISION NOT NULL DEFAULT 90.0,
        temperatura_concreto_c DOUBLE PRECISION NOT NULL,
        temperatura_ambiente_c DOUBLE PRECISION,
        humedad_relativa_pct DOUBLE PRECISION,
        condicion_observada TEXT NOT NULL,
        checklist_json TEXT NOT NULL,
        motivo TEXT NOT NULL,
        operador TEXT,
        supervisor TEXT NOT NULL,
        activo INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ajustes_prediccion_campo (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        zona_base_id INTEGER NOT NULL REFERENCES zonas_colado(id) ON DELETE CASCADE,
        fecha_hora TEXT NOT NULL,
        hora_salida_planta_zona_base TEXT NOT NULL,
        edad_observada_liberacion_h DOUBLE PRECISION NOT NULL,
        madurez_calculada_pct DOUBLE PRECISION NOT NULL,
        temperatura_concreto_c DOUBLE PRECISION,
        motivo TEXT,
        operador TEXT,
        supervisor TEXT,
        activo INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ensayos_cilindro_deslizamiento (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        t_fabricacion TEXT NOT NULL,
        resultado_4h TEXT NOT NULL DEFAULT 'PENDIENTE',
        fecha_hora_4h TEXT,
        resultado_5h TEXT NOT NULL DEFAULT 'PENDIENTE',
        fecha_hora_5h TEXT,
        resultado_6h TEXT NOT NULL DEFAULT 'PENDIENTE',
        fecha_hora_6h TEXT,
        escenario_activo TEXT,
        estado TEXT NOT NULL DEFAULT 'ESPERANDO_ENSAYO',
        operador TEXT,
        supervisor TEXT,
        observaciones TEXT,
        updated_at TEXT NOT NULL,
        layer_thickness_cm DOUBLE PRECISION NOT NULL DEFAULT 30.0,
        total_layers INTEGER NOT NULL DEFAULT 7,
        start_zone INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS programas_deslizado (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        ensayo_cilindro_id INTEGER REFERENCES ensayos_cilindro_deslizamiento(id) ON DELETE SET NULL,
        t_fabricacion TEXT NOT NULL,
        escenario TEXT NOT NULL,
        step_cm DOUBLE PRECISION NOT NULL,
        step_minutes DOUBLE PRECISION NOT NULL,
        layer_thickness_cm DOUBLE PRECISION NOT NULL,
        total_layers INTEGER NOT NULL,
        start_zone INTEGER NOT NULL DEFAULT 1,
        layer_interval_minutes DOUBLE PRECISION NOT NULL,
        speed_cm_min DOUBLE PRECISION NOT NULL,
        speed_cm_h DOUBLE PRECISION NOT NULL,
        activo INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS programas_deslizado_capas (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        programa_id INTEGER NOT NULL REFERENCES programas_deslizado(id) ON DELETE CASCADE,
        capa_numero INTEGER NOT NULL,
        zona_numero INTEGER NOT NULL,
        hora_programada TEXT NOT NULL,
        offset_min DOUBLE PRECISION NOT NULL,
        estado TEXT NOT NULL DEFAULT 'PROGRAMADA',
        UNIQUE(programa_id, capa_numero)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS turnos_operacion (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        operador TEXT NOT NULL,
        inicio_turno TEXT NOT NULL,
        fin_turno TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS turnos_operacion_detalle (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        turno TEXT NOT NULL,
        operador TEXT,
        inicio_turno TEXT NOT NULL,
        fin_turno TEXT,
        nivel_fin_turno_m DOUBLE PRECISION,
        avance_parcial_m DOUBLE PRECISION,
        avance_acumulado_m DOUBLE PRECISION,
        ritmo_cm_h DOUBLE PRECISION,
        observaciones TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS fotografias_evidencia (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        zona_colado_id INTEGER REFERENCES zonas_colado(id) ON DELETE SET NULL,
        fecha_hora TEXT NOT NULL,
        elevacion_cm DOUBLE PRECISION,
        descripcion TEXT,
        operador TEXT,
        imagen_data_url TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS lecturas_desplome (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        fecha_hora TEXT NOT NULL,
        punto TEXT NOT NULL,
        direccion TEXT NOT NULL,
        lectura_mm DOUBLE PRECISION NOT NULL,
        tolerancia_mm DOUBLE PRECISION,
        estado TEXT NOT NULL,
        operador TEXT,
        observaciones TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ajustes_modelo (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        mezcla_id INTEGER REFERENCES mezclas(id) ON DELETE SET NULL,
        colado_id INTEGER REFERENCES colados(id) ON DELETE CASCADE,
        fecha_hora TEXT NOT NULL,
        madurez_objetivo_h_eq DOUBLE PRECISION,
        umbral_prepararse DOUBLE PRECISION,
        umbral_deslizar DOUBLE PRECISION,
        umbral_sobremadurez DOUBLE PRECISION,
        tolerancia_velocidad_min_cm_h DOUBLE PRECISION,
        tolerancia_velocidad_max_cm_h DOUBLE PRECISION,
        operador TEXT,
        supervisor TEXT,
        justificacion TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reportes_generados (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        colado_id INTEGER NOT NULL REFERENCES colados(id) ON DELETE CASCADE,
        tipo TEXT NOT NULL,
        fecha_hora TEXT NOT NULL,
        resumen_json TEXT NOT NULL
    )
    """,
]


def init_postgres_db(conn) -> None:
    for statement in POSTGRES_SCHEMA:
        conn.execute(statement)
    _seed_defaults(conn)
    conn.commit()


def _seed_defaults(conn) -> None:
    conn.execute(
        """
        INSERT INTO configuracion_molde(
            nombre, altura_molde_m, altura_zona_m, zonas_por_molde,
            velocidad_objetivo_cm_h, avance_objetivo_cm_5min,
            residencia_minima_h, residencia_preferente_h
        )
        VALUES ('Default 1.20m', 1.20, 0.30, 4, 30, 3.0, 4.0, 4.5)
        ON CONFLICT (nombre) DO NOTHING
        """
    )
    conn.execute(
        """
        UPDATE configuracion_molde
        SET velocidad_objetivo_cm_h = ?, avance_objetivo_cm_5min = ?
        WHERE nombre = 'Default 1.20m'
        """,
        (DEFAULT_ADVANCE_SPEED_CM_H, DEFAULT_ADVANCE_CM),
    )
    conn.execute(
        """
        INSERT INTO proyectos(nombre, cliente, obra, ubicacion, elemento, activo)
        VALUES ('Seybaplaya', 'Cliente pendiente', 'Silos de concreto', 'Seybaplaya, Campeche', 'Silo', 1)
        ON CONFLICT (nombre) DO NOTHING
        """
    )
    conn.execute(
        """
        INSERT INTO schema_migrations(version, applied_at, description)
        VALUES (?, ?, ?)
        ON CONFLICT (version) DO NOTHING
        """,
        (SCHEMA_VERSION, datetime.now().isoformat(timespec="seconds"), SCHEMA_DESCRIPTION),
    )


__all__ = ["SCHEMA_DESCRIPTION", "SCHEMA_VERSION", "init_postgres_db"]
